# fly.toml file generated for holy-grass-8371 on 2021-04-06T14:31:33-04:00

app = "twoclickmail"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
# required because we can't infer your binary's name
cmd = "./twoclickmail"

[env]
PORT = "5000"

[[services]]
internal_port = 5000
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

# [[services.ports]]
# handlers = ["http"]
# port = "80"

# [[services.ports]]
# handlers = ["tls", "http"]
# port = "443"

# [[services.http_checks]]
# path            = "/health"
# method          = "get"
# timeout         = "2000ms"
# interval        = "10000ms"
# protocol        = "http"
# grace_period    = "5s"
# tls_skip_verify = false